<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>x64</Platforms>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <Target Name="CopyThirdPartyLibraries_win64" AfterTargets="Build"
          Condition="'$(OS)' == 'Windows_NT'">
    <ItemGroup>
      <DLLSource Include="../NativeLib/bin/glfw3.dll"></DLLSource>
    </ItemGroup>
    <Copy SourceFiles="@(DLLSource)"
          DestinationFolder="$(OutputPath)"
          SkipUnchangedFiles="True"/>
  </Target>

  <Target Name="CopyNativeLib_win64_debug" AfterTargets="Build" 
          Condition="'$(Configuration)' == 'Debug' AND '$(OS)' == 'Windows_NT'">
    <ItemGroup>
      <DLLSource Include="../NativeLib/build/mingw/x64/debug/*.dll"></DLLSource>
    </ItemGroup>
    <Copy SourceFiles="@(DLLSource)"
          DestinationFolder="$(OutputPath)"
          SkipUnchangedFiles="True"/>
  </Target>

  <Target Name="CopyNativeLib_win64_release" AfterTargets="Build" 
          Condition="'$(Configuration)' == 'Release' AND '$(OS)' == 'Windows_NT'">
    <ItemGroup>
      <DLLSource Include="../NativeLib/build/mingw/x64/release/*.dll"></DLLSource>
    </ItemGroup>
    <Copy SourceFiles="@(DLLSource)"
          DestinationFolder="$(OutputPath)" 
          SkipUnchangedFiles="True"/>
  </Target>

  <Target Name="CopyNativeLib_linux64_debug" AfterTargets="Build"
          Condition="'$(Configuration)' == 'Debug' AND '$(OS)' == 'Unix'">
    <ItemGroup>
      <SOSource Include="../NativeLib/build/linux/x64/debug/*.so"></SOSource>
    </ItemGroup>
    <Copy SourceFiles="@(SOSource)"
          DestinationFolder="$(OutputPath)"
          SkipUnchangedFiles="True"/>
  </Target>

  <Target Name="CopyNativeLib_linux64_release" AfterTargets="Build"
          Condition="'$(Configuration)' == 'Release' AND '$(OS)' == 'Unix'">
    <ItemGroup>
      <SOSource Include="../NativeLib/build/linux/x64/release/*.so"></SOSource>
    </ItemGroup>
    <Copy SourceFiles="@(SOSource)"
          DestinationFolder="$(OutputPath)"
          SkipUnchangedFiles="True"/>
  </Target>

  <Target Name="CopyResources" AfterTargets="Build">
    <ItemGroup>
      <Resources Include="../Resources/Shaders/bin/*.spv"></Resources>
    </ItemGroup>
    <Copy SourceFiles="@(Resources)"
          DestinationFolder="$(OutputPath)"
          SkipUnchangedFiles="True"/>
  </Target>

</Project>
